# Generated by Django 3.2.12 on 2022-02-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('recommendation', models.TextField()),
                ('action_work_required', models.TextField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('vehicle_reg', models.CharField(max_length=10)),
                ('start_mileage', models.IntegerField()),
                ('end_mileage', models.IntegerField()),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=300)),
                ('job_number', models.CharField(max_length=100)),
                ('client_signature', models.TextField()),
                ('engineer_signature', models.TextField()),
                ('manager_signature', models.TextField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.client')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.engineer')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.manager')),
            ],
            options={
                'verbose_name': 'Daily Work Sheet',
                'verbose_name_plural': 'Daily Work Sheets',
            },
        ),
    ]
