# Generated by Django 3.2.12 on 2022-02-27 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220227_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworksheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
