# Generated by Django 3.2.12 on 2022-02-27 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailyworksheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworksheet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
