# Generated by Django 3.2.12 on 2022-02-27 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailyworksheet_work_sheet_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworksheet',
            name='work_sheet_images',
            field=models.FileField(default=django.utils.timezone.now, upload_to='work_sheet/'),
            preserve_default=False,
        ),
    ]
