# Generated by Django 3.2.12 on 2022-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dailyworksheet_work_sheet_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworksheet',
            name='client',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworksheet',
            name='engineer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworksheet',
            name='manager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
