# Generated by Django 3.2.12 on 2022-02-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dailyworksheet_client_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyworksheet',
            name='manager_signature',
        ),
    ]
